spring:
  profiles:
    active: core,database

server:
  port: 8080
dubbo:
  application:
    logger: slf4j
    name: '***'
  registry:
    address: '***'
    parameters:
      namespace: '***'
  protocol:
    name: dubbo
    port: -1
